REM Ths file will remove unnecessary bak dirs that were generated by the jbuilder

@echo off

del .\And\conprod\*.*~
del .\And\consumer\*.*~
del .\And\producer\*.*~

del .\Or\conprod\*.*~
del .\Or\consumer\*.*~
del .\Or\producer\*.*~

del .\Seq\conprod\*.*~
del .\Seq\consumer\*.*~
del .\Seq\producer\*.*~


del .\Not_1\consumer\*.*~
del .\Not_1\producer\*.*~
del .\Not_1\consumer\*.~*
del .\Not_1\producer\*.~*

del .\Not_2\conprod\*.*~
del .\Not_2\consumer\*.*~
del .\Not_2\producer\*.*~
del .\Not_2\conprod\*.~*
del .\Not_2\consumer\*.~*
del .\Not_2\producer\*.~*


pause