REM Ths file will remove unnecessary bak dirs that were generated by the jbuilder

@echo off

del .\ControlCenter\bak\controlcenter\*.*
del .\ControlCenter\*.*~
rmdir .\ControlCenter\bak\controlcenter
rmdir .\ControlCenter\bak
del .\ControlCenter\source\*.*~
del .\ControlCenter\source\controlcenter\*.*~
del .\ControlCenter\source\controlcenter\*.~*

del .\Makefits_AirForce\bak\Makefits\*.*
del .\Makefits_AirForce\*.*~
rmdir .\Makefits_AirForce\bak\Makefits
rmdir .\Makefits_AirForce\bak
del .\Makefits_AirForce\source\*.*~
del .\Makefits_AirForce\source\Makefits\*.*~
del .\Makefits_AirForce\source\Makefits\*.~*

del .\Makefits_Navy\bak\Makefits\*.*
del .\Makefits_Navy\*.*~
rmdir .\Makefits_Navy\bak\Makefits
rmdir .\Makefits_Navy\bak
del .\Makefits_Navy\source\*.*~
del .\Makefits_Navy\source\Makefits\*.*~
del .\Makefits_Navy\source\Makefits\*.~*


pause
