REM Ths file will remove unnecessary bak dirs that were generated by the jbuilder

@echo off

del .\*.*~
del .\*.~*

del .\sentinel\*.*~
del .\sentinel\*.~*

del .\sentinel\led\*.*~
del .\sentinel\led\*.~*

del .\sentinel\ged\*.*~
del .\sentinel\ged\*.~*

del .\sentinel\comm\*.*~
del .\sentinel\comm\*.~*


pause